SELECT  aba.attribute1,
        aba.attribute2,
        aba.attribute3,
        aba.attribute4,
        aba.attribute5,
        aba.attribute6,
        aba.attribute7,
        aba.attribute8,
        aba.attribute9,
        aba.attribute10,
        aba.attribute11,
        aba.attribute12,
        aba.attribute13,
        aba.attribute14,
        aba.attribute15,
        aba.currency_code bank_account_currency,
        abb.address_line1,
        abb.address_line2,
        abb.address_line3,
        abb.address_line4,
        aba.BANK_ACCOUNT_NAME bank_account_name,
        aba.bank_account_num bank_Account_number,
        abb.bank_branch_name,
        abb.bank_num bank_branch_number,
        abb.bank_name,
        abb.bank_number bank_number,
        fu_cr.user_name created_by,
        abau.creation_date,
        -- bank account creation date or bank account to vendor association?
        abau.start_date effective_date_from,
        abau.end_date effective_date_to,
        abau.last_update_date,
        fu_upd.user_name last_updated_by,
        abau.primary_flag,
        pv.vendor_name supplier_name,
        TO_NUMBER(pv.segment1) supplier_number,
        pvs.VENDOR_SITE_CODE supplier_site_name,
        pv.vendor_id,
        pvs.vendor_site_id,
        aba.bank_account_id,
        abb.bank_branch_id
FROM    po_vendors              pv,
        po_vendor_sites         pvs,
        ap_bank_accounts        aba,
        ap_bank_account_uses    abau,
        ap_bank_branches        abb,
        fnd_user                fu_cr,
        fnd_user                fu_upd
WHERE   abau.external_bank_account_id=aba.bank_account_id(+)   
AND     aba.bank_branch_id = abb.bank_branch_id   
AND     abau.vendor_id = pv.vendor_id(+)   
AND     abau.vendor_site_id = pvs.vendor_site_id(+)   
AND     abau.created_by = fu_cr.user_id   
AND     abau.last_updated_by = fu_upd.user_id;
