SELECT  aerh.accounting_date,
        aerh.attribute1,
        aerh.attribute2,
        aerh.attribute3,
        aerh.attribute4,
        aerh.attribute5,
        aerh.attribute6,
        aerh.attribute7,
        aerh.attribute8,
        aerh.attribute9,
        aerh.attribute10,
        aerh.attribute11,
        aerh.attribute12,
        aerh.attribute13,
        aerh.attribute14,
        aerh.attribute15,
        fu_cr.user_name created_by,
        aerh.creation_date,
        aerh.description,
        xpp.full_name employee_name,
        xpp.employee_number,
        aerh.total expense_report_amount,
        aerh.week_end_date expense_report_date,
        aer.report_type expense_report_template,
        alc.displayed_field expense_status_code,
        gcc.segment1,
        SUBSTR(apps.gl_flexfields_pkg.get_description_sql( gcc.chart_of_accounts_id,1,gcc.segment1),1,40) segment1_desc,
        gcc.segment2,
        SUBSTR(apps.gl_flexfields_pkg.get_description_sql( gcc.chart_of_accounts_id,2,gcc.segment2),1,40) segment1_desc,
        gcc.segment3,
        SUBSTR(apps.gl_flexfields_pkg.get_description_sql( gcc.chart_of_accounts_id,3,gcc.segment3),1,40) segment1_desc,
        gcc.segment4,
        SUBSTR(apps.gl_flexfields_pkg.get_description_sql( gcc.chart_of_accounts_id,4,gcc.segment4),1,40) segment1_desc,
        gcc.segment5,
        SUBSTR(apps.gl_flexfields_pkg.get_description_sql( gcc.chart_of_accounts_id,5,gcc.segment5),1,40) segment1_desc,
        gcc.segment6,
        SUBSTR(apps.gl_flexfields_pkg.get_description_sql( gcc.chart_of_accounts_id,6,gcc.segment6),1,40) segment1_desc,
        gcc.segment7,
        SUBSTR(apps.gl_flexfields_pkg.get_description_sql( gcc.chart_of_accounts_id,7,gcc.segment7),1,40) segment1_desc,
        gcc.segment8,
        SUBSTR(apps.gl_flexfields_pkg.get_description_sql( gcc.chart_of_accounts_id,8,gcc.segment8),1,40) segment1_desc,
        gcc.segment9,
        SUBSTR(apps.gl_flexfields_pkg.get_description_sql( gcc.chart_of_accounts_id,9,gcc.segment9),1,40) segment1_desc,
        aerh.default_currency_code invoice_currency,
        aerh.invoice_num invoice_number,
        aerh.last_update_date,
        fu_upd.user_name last_updated_by,
        DECODE(aerh.workflow_approved_flag,'Y','Yes','M','Yes','R','Yes','No') reviewed_by_management,
        DECODE(aerh.workflow_approved_flag,'Y','Yes','M','Yes','R','Yes','No') reviewed_by_payables,
        aerh.workflow_approved_flag,
        DECODE(NVL(aerh. prepay_apply_flag,'N'),'N','No','Yes') prepay_applied_flag,
        xpp.person_id,
        aerh.report_header_id
FROM    ap_expense_report_headers_all       aerh,
        ap_expense_reports_all              aer,
        fnd_user                            fu_cr,
        fnd_user                            fu_upd,
        ap_lookup_codes                     alc,
        gl_code_combinations                gcc,
        per_people_x                        xpp
WHERE   aerh.created_by = fu_cr.user_id
AND     aerh.expense_report_id = aer.expense_report_id
AND     aerh.last_updated_by = fu_upd.user_id
AND     aerh.expense_status_code = alc.lookup_code(+)
AND     alc.lookup_type (+)= 'EXPENSE REPORT STATUS'
AND     aerh.EMPLOYEE_CCID = gcc.code_combination_id(+)
AND     aerh.employee_id = xpp.person_id(+);
